### ISSUE TITLE
IDE Error

### ISSUE THREAD

**Issue by squi2rel** [Zelaux/ArcSupportPlugin#1]
1/3
java.lang.IllegalStateException: Array is empty.
	at arc.struct.Seq.pop(Seq.java:719)
	at arc.util.pooling.Pool.obtain(Pool.java:40)
	at com.zelaux.arcplugin.colorExpression.ColorExpressionResolver.resolve(ColorExpressionResolver.java:82)
	at com.zelaux.arcplugin.colorExpression.ColorExpressionResolver.resolveColorSequence(ColorExpressionResolver.java:38)
	at com.zelaux.arcplugin.colorExpression.ColorExpressionResolver.resolveColorSequence(ColorExpressionResolver.java:41)
	at com.zelaux.arcplugin.colorExpression.ColorExpressionResolver.resolveColorSequence(ColorExpressionResolver.java:47)
	at com.zelaux.arcplugin.colorExpression.ColorExpressionResolver.resolveColor(ColorExpressionResolver.java:28)
	at com.zelaux.arcplugin.expressions.resolve.methods.StaticSetColorExpression.lambda$new$0(StaticSetColorExpression.java:24)
	at com.zelaux.arcplugin.utils.LazyValue.get(LazyValue.java:34)
	at com.zelaux.arcplugin.expressions.resolve.methods.StaticSetColorExpression.apply(StaticSetColorExpression.java:44)
	at com.zelaux.arcplugin.colorExpression.ColorFieldAssignLineMarkerProvider.expressionParserSequenceFrom(ColorFieldAssignLineMarkerProvider.java:59)
	at com.zelaux.arcplugin.colorExpression.ColorFieldAssignLineMarkerProvider.expressionParserSequenceFrom(ColorFieldAssignLineMarkerProvider.java:17)
	at com.zelaux.arcplugin.marker.colorexp.ExpressionSequenceParserLineMarkerProvider.lambda$collectSlowLineMarkers$0(ExpressionSequenceParserLineMarkerProvider.java:43)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
	at com.zelaux.arcplugin.marker.colorexp.ExpressionSequenceParserLineMarkerProvider.collectSlowLineMarkers(ExpressionSequenceParserLineMarkerProvider.java:42)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:223)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:114)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

2/3
java.lang.IllegalArgumentException: object cannot be null.
	at arc.util.pooling.Pool.free(Pool.java:50)
	at com.zelaux.arcplugin.colorExpression.ColorFieldAssignLineMarkerProvider.expressionParserSequenceFrom(ColorFieldAssignLineMarkerProvider.java:61)
	at com.zelaux.arcplugin.colorExpression.ColorFieldAssignLineMarkerProvider.expressionParserSequenceFrom(ColorFieldAssignLineMarkerProvider.java:17)
	at com.zelaux.arcplugin.marker.colorexp.ExpressionSequenceParserLineMarkerProvider.lambda$collectSlowLineMarkers$0(ExpressionSequenceParserLineMarkerProvider.java:43)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
	at com.zelaux.arcplugin.marker.colorexp.ExpressionSequenceParserLineMarkerProvider.collectSlowLineMarkers(ExpressionSequenceParserLineMarkerProvider.java:42)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:223)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:114)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

3/3
java.lang.NullPointerException: Cannot invoke "arc.graphics.Color.set(arc.graphics.Color)" because "target" is null
	at com.zelaux.arcplugin.expressions.resolve.methods.StaticSetColorExpression.apply(StaticSetColorExpression.java:46)
	at com.zelaux.arcplugin.expressions.resolve.methods.LerpExpression.apply(LerpExpression.java:71)
	at com.zelaux.arcplugin.expressions.resolve.ArcColorExpressionSequence.applyColorUntil(ArcColorExpressionSequence.java:50)
	at com.zelaux.arcplugin.expressions.resolve.ArcColorExpressionSequence.calculateResultAwtColor(ArcColorExpressionSequence.java:18)
	at com.zelaux.arcplugin.expressions.render.ArcColorExpressionSequenceRenderer.getIconColor(ArcColorExpressionSequenceRenderer.java:113)
	at com.zelaux.arcplugin.expressions.render.ArcColorExpressionSequenceRenderer.getIcon(ArcColorExpressionSequenceRenderer.java:108)
	at com.zelaux.arcplugin.marker.colorexp.ExpressionSequenceParserLineMarkerProvider$MyInfo.<init>(ExpressionSequenceParserLineMarkerProvider.java:101)
	at com.zelaux.arcplugin.marker.colorexp.ExpressionSequenceParserLineMarkerProvider.lambda$collectSlowLineMarkers$0(ExpressionSequenceParserLineMarkerProvider.java:48)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
	at com.zelaux.arcplugin.marker.colorexp.ExpressionSequenceParserLineMarkerProvider.collectSlowLineMarkers(ExpressionSequenceParserLineMarkerProvider.java:42)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:223)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:114)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Zelaux** [comment]
I guess `arc.util.pooling.Pool` is not thread save

**Comment by Zelaux** [comment]
Fixed in 0.8.1( It will available to download after moderation)
![image](https://github.com/Zelaux/ArcSupportPlugin/assets/58040045/ec706bda-0e28-40f9-b4d8-9a2cef874f47)
